export type Tvehiculo = {
    id: number;
    modelo: string;
    tipo: string;
    año: string;
    kilometraje: number;
    chasis: string;
    motor: string;
    combustible: string;
    aceite_motor: string;
    aceite_caja: string;
    filtro_aceite: number;
    filtro_aire_primario: string;  
    filtro_aire_secundario: string;
    filtro_combustible_primario: string;
    filtro_combustible_secundario: string;
    neumaticos_delanteros: string;
    neumaticos_traseros: string;
    observaciones: string;
};